# Generated by Django 4.2.7 on 2026-07-14 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('url', models.URLField()),
                ('phishing_score', models.FloatField()),
                ('non_phishing_score', models.FloatField()),
                ('is_ip_address', models.IntegerField(default=0)),
                ('long_url', models.IntegerField(default=0)),
                ('shor_turl', models.IntegerField(default=0)),
                ('symbol', models.IntegerField(default=0)),
                ('redirect', models.IntegerField(default=0)),
                ('prefix_suffix', models.IntegerField(default=0)),
                ('subdomains', models.IntegerField(default=0)),
                ('https', models.IntegerField(default=0)),
                ('domainreglen', models.IntegerField(default=0)),
                ('favicon', models.IntegerField(default=0)),
                ('non_std_port', models.IntegerField(default=0)),
                ('httpsdomainurl', models.IntegerField(default=0)),
                ('requesturl', models.IntegerField(default=0)),
                ('anchorurl', models.IntegerField(default=0)),
                ('linksinscripttags', models.IntegerField(default=0)),
                ('serverformhandler', models.IntegerField(default=0)),
                ('infoemail', models.IntegerField(default=0)),
                ('abnormalurl', models.IntegerField(default=0)),
                ('websiteforwarding', models.IntegerField(default=0)),
                ('statusbarcust', models.IntegerField(default=0)),
                ('disablerightclick', models.IntegerField(default=0)),
                ('usingpopupwindow', models.IntegerField(default=0)),
                ('iframeredirection', models.IntegerField(default=0)),
                ('ageofdomain', models.IntegerField(default=0)),
                ('dnsrecording', models.IntegerField(default=0)),
                ('websitetraffic', models.IntegerField(default=0)),
                ('pagerank', models.IntegerField(default=0)),
                ('googleindex', models.IntegerField(default=0)),
                ('linkspointingtopage', models.IntegerField(default=0)),
                ('statsreport', models.IntegerField(default=0)),
                ('stats_report', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
