# Generated by Django 4.2.7 on 2026-07-14 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.CharField(blank=True, max_length=320)),
                ('subject', models.TextField(blank=True)),
                ('body_phish_score', models.FloatField(default=0.0)),
                ('header_status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('header_spf', models.BooleanField(blank=True, null=True)),
                ('header_dkim', models.BooleanField(blank=True, null=True)),
                ('header_dmarc', models.BooleanField(blank=True, null=True)),
                ('domain', models.TextField(blank=True)),
                ('valid', models.BooleanField(blank=True, null=True)),
                ('block', models.BooleanField(blank=True, null=True)),
                ('disposable', models.BooleanField(blank=True, null=True)),
                ('email_forwarder', models.BooleanField(blank=True, null=True)),
                ('mx_host', models.TextField(blank=True)),
                ('mx_ip', models.TextField(blank=True)),
                ('mx_info', models.TextField(blank=True)),
                ('risk', models.IntegerField(blank=True, null=True)),
                ('final_verdict', models.CharField(choices=[('clean', 'Clean'), ('suspicious', 'Suspicious'), ('phishing', 'Phishing')], default='clean', max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
